global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: scrapemodem
  scrape_interval: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - scrapemodem:5000
- job_name: blackbox
  metrics_path: /probe
  params:
    module: [icmp]
  scrape_interval: 1s
  static_configs:
    - targets:
      - 8.8.8.8                     # Google DNS
      - dns4.imoncommunications.net # Imon DNS
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: prometheus-blackbox:9115

