{
 "title": "Home Network Status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ICMP Ping (Google/Imon DNS)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "probe_duration_seconds" }
   ]
  },
  {
   "title": "ICMP Success (Google DNS)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"8.8.8.8\"}"
    }
   ]
  },
  {
   "title": "Downstream Bonded Channel (Power)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "dBmV" }
   ],
   "targets": [
    { "expr": "modem_bonded_channel" }
   ]
  },
  {
   "title": "Upstream Bonded Channel (Power)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "dBmV" }
   ],
   "targets": [
    {
     "expr": "modem_us_bonded_channel{id=~\"1|2|3\"}"
    }
   ]
  }
 ]
}